### ISSUE TITLE
Recovering leader may not have the latest data

### ISSUE THREAD

**Issue by apoydence** [apoydence/talaria#2]
So this can happen when the leader is killed and the replica (*R1*) with offset *N* is elected the leader. Then a different replica (*R2*) with an offset *M* where *M > N* tries to read from the new leader. 

It was first noticed in the `chaos_test.go` 

The reading replica will panic when telling the leader to seek to index it does not yet have:

```
00:43:24:000 initWriter > CRIT 025 Unable to seek to index 30: EOF
panic: Unable to seek to index 30: EOF

goroutine 31 [running]:
github.com/op/go-logging.(*Logger).Panicf(0xc2080a6e70, 0x5b1b50, 0x1e, 0xc2080b9e88, 0x2, 0x2)
	/Users/pivotal/workspace/Go/src/github.com/op/go-logging/logger.go:189 +0x1bc
github.com/apoydence/talaria/logging.Logger.Panicf(0xc2080a6e70, 0x5b1b50, 0x1e, 0xc2080b9e88, 0x2, 0x2)
	/Users/pivotal/workspace/Go/src/github.com/apoydence/talaria/logging/logging.go:73 +0x68
github.com/apoydence/talaria/broker.(*ReplicatedFileManager).initWriter(0xc2080505f0, 0x1e, 0x0, 0xc208114590, 0x1, 0x8, 0x1449060, 0xc20807c180, 0xc2080dc640, 0x0)
	/Users/pivotal/workspace/Go/src/github.com/apoydence/talaria/broker/replicated_file_manager.go:145 +0x496
github.com/apoydence/talaria/broker.(*ReplicatedFileManager).copyToWriter(0xc2080505f0, 0xc2080dc640, 0x1449060, 0xc20807c180)
	/Users/pivotal/workspace/Go/src/github.com/apoydence/talaria/broker/replicated_file_manager.go:118 +0x1be
created by github.com/apoydence/talaria/broker.(*ReplicatedFileManager).setupCopy
	/Users/pivotal/workspace/Go/src/github.com/apoydence/talaria/broker/replicated_file_manager.go:95 +0x772
```

**Comment by apoydence** [comment]
This obviously deals with architecture decisions that I haven't decided on yet. I want to clear this up with very little code... Meaning I'm going to bite off small pieces at the expense of the solution being rough.

With that said, my plan is to have *R2* send a message to *R1* (new leader) telling it is not a valid leader. The leader will then panic (I know... heavy handed) forcing a new election.

This obviously a HORRIBLE idea and can't live long... And it won't. It also assumes the broker is running with something like [monit](https://mmonit.com/monit/).
